### ISSUE TITLE
Istio timeout by endpoint

### ISSUE THREAD

**Issue by EvaldoNeto** [servicemesh-es/servicemesh.es#35]
In the comparison table is states that is not possible to configure timeout for each endpoint, but it is. 

Example:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-vs
spec:
  hosts:
  - "myhost.com"
  gateways:
  - my-gateway
  http:
  - match:
    - uri:
        prefix: /path1
    route:
    - destination:
        host: service-1.default.svc.cluster.local
        port:
          number: 443
    timeout: 40s
  - match:
    - uri:
        prefix: /path2
    route:
    - destination:
        host: service-1.default.svc.cluster.local
        port:
          number: 443
    timeout: 15s
 ```
